package com.example.taskmanagement.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

/**
 * Represents a Task entity in the database.
 * Each instance of this class corresponds to a row in the "tasks" table.
 */
@Entity
@Table(name = "tasks")
public class Task {

    /**
     * The unique identifier for the task.
     * This is the primary key.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The title of the task.
     * This column cannot be null.
     */
    @Column(nullable = false)
    private String title;

    /**
     * A detailed description of the task.
     * This can be a longer text.
     */
    @Column(columnDefinition = "TEXT")
    private String description;

    /**
     * The completion status of the task.
     * Defaults to false.
     */
    @Column(nullable = false)
    private Boolean completed;

    // --- Getters and Setters ---
    // These are methods that allow us to access and modify the private fields.

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Boolean getCompleted() {
        return completed;
    }

    public void setCompleted(Boolean completed) {
        this.completed = completed;
    }
}
